# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Main_Ui(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(932, 825)
        self.gridLayout_2 = QtWidgets.QGridLayout(home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.HeaderToolBar = CommandBar(home)
        self.HeaderToolBar.setObjectName("HeaderToolBar")
        self.mainLayout.addWidget(self.HeaderToolBar)
        self.Layout_content = QtWidgets.QHBoxLayout()
        self.Layout_content.setObjectName("Layout_content")
        self.ActionMenuBar = SimpleCardWidget(home)
        self.ActionMenuBar.setObjectName("ActionMenuBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ActionMenuBar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SimpleCardWidget = SimpleCardWidget(self.ActionMenuBar)
        self.SimpleCardWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SimpleCardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IconWidget = IconWidget(self.SimpleCardWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/jigsaw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.IconWidget.setIcon(icon)
        self.IconWidget.setObjectName("IconWidget")
        self.horizontalLayout.addWidget(self.IconWidget)
        self.CaptionLabel = CaptionLabel(self.SimpleCardWidget)
        self.CaptionLabel.setProperty("pixelFontSize", 20)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout.addWidget(self.CaptionLabel)
        self.verticalLayout_2.addWidget(self.SimpleCardWidget)
        self.TreeWidget = TreeWidget(self.ActionMenuBar)
        self.TreeWidget.setObjectName("TreeWidget")
        self.TreeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.TreeWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.Layout_content.addWidget(self.ActionMenuBar)
        self.ScriptEditBar = SimpleCardWidget(home)
        self.ScriptEditBar.setObjectName("ScriptEditBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ScriptEditBar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.ScriptEditBar)
        self.tabWidget.setObjectName("tabWidget")
        self.VisualizationTab = QtWidgets.QWidget()
        self.VisualizationTab.setObjectName("VisualizationTab")
        self.gridLayout = QtWidgets.QGridLayout(self.VisualizationTab)
        self.gridLayout.setObjectName("gridLayout")
        self.ListWidget = ListWidget(self.VisualizationTab)
        self.ListWidget.setObjectName("ListWidget")
        self.gridLayout.addWidget(self.ListWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.VisualizationTab, "")
        self.SourceCodeTab = QtWidgets.QWidget()
        self.SourceCodeTab.setObjectName("SourceCodeTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SourceCodeTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PlainTextEdit = PlainTextEdit(self.SourceCodeTab)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.gridLayout_3.addWidget(self.PlainTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.SourceCodeTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.Layout_content.addWidget(self.ScriptEditBar)
        self.AttributeBar = SimpleCardWidget(home)
        self.AttributeBar.setObjectName("AttributeBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.AttributeBar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ListWidget_2 = ListWidget(self.AttributeBar)
        self.ListWidget_2.setObjectName("ListWidget_2")
        self.verticalLayout_3.addWidget(self.ListWidget_2)
        self.Layout_content.addWidget(self.AttributeBar)
        self.Layout_content.setStretch(0, 3)
        self.Layout_content.setStretch(1, 9)
        self.Layout_content.setStretch(2, 2)
        self.mainLayout.addLayout(self.Layout_content)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 15)
        self.gridLayout_2.addLayout(self.mainLayout, 0, 0, 1, 1)

        self.retranslateUi(home)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Form"))
        self.CaptionLabel.setText(_translate("home", "动作列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VisualizationTab), _translate("home", "可视化"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SourceCodeTab), _translate("home", "源代码"))
from qfluentwidgets import CaptionLabel, CommandBar, IconWidget, ListWidget, PlainTextEdit, SimpleCardWidget, TreeWidget
from src.resources.img import  rpa_rc
