# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotmain_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Robot(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 348)
        self.background = SimpleCardWidget(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 401, 351))
        self.background.setObjectName("background")
        self.seting = TitleLabel(self.background)
        self.seting.setGeometry(QtCore.QRect(10, 10, 123, 38))
        self.seting.setObjectName("seting")
        self.serverhostlabel = CaptionLabel(self.background)
        self.serverhostlabel.setGeometry(QtCore.QRect(30, 70, 71, 16))
        self.serverhostlabel.setObjectName("serverhostlabel")
        self.serverhost = LineEdit(self.background)
        self.serverhost.setGeometry(QtCore.QRect(30, 100, 291, 33))
        self.serverhost.setObjectName("serverhost")
        self.StrongBodyLabel = StrongBodyLabel(self.background)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(20, 320, 111, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.initbutton = PrimaryPushButton(self.background)
        self.initbutton.setGeometry(QtCore.QRect(300, 310, 81, 32))
        self.initbutton.setObjectName("initbutton")
        self.setserverhost = ToolButton(self.background)
        self.setserverhost.setGeometry(QtCore.QRect(340, 100, 38, 32))
        self.setserverhost.setObjectName("setserverhost")
        self.projectdir = LineEdit(self.background)
        self.projectdir.setGeometry(QtCore.QRect(30, 170, 291, 33))
        self.projectdir.setObjectName("projectdir")
        self.setprojectdir = ToolButton(self.background)
        self.setprojectdir.setGeometry(QtCore.QRect(340, 170, 38, 32))
        self.setprojectdir.setObjectName("setprojectdir")
        self.projectlabel = CaptionLabel(self.background)
        self.projectlabel.setGeometry(QtCore.QRect(30, 150, 51, 16))
        self.projectlabel.setObjectName("projectlabel")
        self.username = LineEdit(self.background)
        self.username.setGeometry(QtCore.QRect(30, 240, 101, 33))
        self.username.setObjectName("username")
        self.usernamelabel = CaptionLabel(self.background)
        self.usernamelabel.setGeometry(QtCore.QRect(40, 220, 70, 15))
        self.usernamelabel.setObjectName("usernamelabel")
        self.passwordlabel = CaptionLabel(self.background)
        self.passwordlabel.setGeometry(QtCore.QRect(170, 220, 70, 15))
        self.passwordlabel.setObjectName("passwordlabel")
        self.PasswordLineEdit = PasswordLineEdit(self.background)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(160, 240, 158, 33))
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")

        #设置背景为黑色
        # self.background 设置主题为Dark
        self.background.setStyleSheet("background-color: rgb(41, 39, 35);")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.seting.setText(_translate("Form", "设置"))
        self.serverhostlabel.setText(_translate("Form", "服务器地址"))
        self.StrongBodyLabel.setText(_translate("Form", "uuid"))
        self.initbutton.setText(_translate("Form", "初始化"))
        self.projectlabel.setText(_translate("Form", "项目地址"))
        self.usernamelabel.setText(_translate("Form", "用户名"))
        self.passwordlabel.setText(_translate("Form", "密码"))
from qfluentwidgets import CaptionLabel, LineEdit, PasswordLineEdit, PrimaryPushButton, SimpleCardWidget, StrongBodyLabel, TitleLabel, ToolButton
